# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdAreas', models.IntegerField()),
                ('NomArea', models.CharField(max_length=20)),
                ('CodArea', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ceco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCeco', models.IntegerField()),
                ('CodCeco', models.CharField(blank=True, max_length=10, null=True)),
                ('NomCeco', models.CharField(blank=True, max_length=100, null=True)),
                ('Budget', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('IdAreas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ctta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCtta', models.IntegerField()),
                ('NomCtta', models.CharField(max_length=100)),
                ('DirCtta', models.CharField(blank=True, max_length=100, null=True)),
                ('RutCtta', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ctto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCtto', models.IntegerField()),
                ('NumCtto', models.CharField(blank=True, max_length=20, null=True)),
                ('DescCtto', models.CharField(blank=True, max_length=100, null=True)),
                ('MonedaCtto', models.CharField(blank=True, max_length=5, null=True)),
                ('ValorCtto', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('EstCtto', models.CharField(blank=True, max_length=4, null=True)),
                ('FechIniCtto', models.DateField()),
                ('FechTerCtto', models.DateField()),
                ('CordCtto', models.CharField(blank=True, max_length=100, null=True)),
                ('Carpeta', models.CharField(blank=True, max_length=30, null=True)),
                ('TipoServ', models.CharField(blank=True, max_length=25, null=True)),
                ('AjusteCom', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('AjustNumEDP', models.CharField(blank=True, max_length=10, null=True)),
                ('AjustValEDP', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('AdjudicCtto', models.CharField(blank=True, max_length=15, null=True)),
                ('LocalCtto', models.CharField(blank=True, max_length=10, null=True)),
                ('TerrenCtto', models.CharField(blank=True, max_length=10, null=True)),
                ('SeguroCtto', models.CharField(blank=True, max_length=10, null=True)),
                ('IdCecoCtto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ceco')),
                ('IdCtta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ctta')),
            ],
        ),
        migrations.CreateModel(
            name='Edp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEDP', models.IntegerField()),
                ('NumEDP', models.CharField(max_length=10)),
                ('ValEDP', models.DecimalField(decimal_places=2, max_digits=21)),
                ('PeriodEDP', models.DateField()),
                ('DevAntEDP', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('RetEDP', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('DevRet', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('Estado', models.CharField(max_length=10)),
                ('FactEDP', models.CharField(blank=True, max_length=30, null=True)),
                ('IdCtto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ctto')),
            ],
        ),
        migrations.CreateModel(
            name='Mdte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdMandante', models.IntegerField()),
                ('NomMandte', models.CharField(max_length=50)),
                ('DirecMandte', models.CharField(max_length=100)),
                ('RutMandte', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomMoneda', models.CharField(max_length=4)),
                ('ValorMoneda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('FechMoneda', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Odc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdODC', models.IntegerField()),
                ('NumODC', models.CharField(max_length=8)),
                ('FechT_ODC', models.DateField(blank=True, null=True)),
                ('ValorODC', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('DescripODC', models.CharField(blank=True, max_length=15, null=True)),
                ('IdCecoODC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ceco')),
                ('IdCtto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ctto')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('slug', models.CharField(default='question', max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ctto',
            name='IdMandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Mdte'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Question'),
        ),
    ]
