# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='IdAreas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ceco',
            name='IdCeco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctta',
            name='IdCtta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctto',
            name='IdCtto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edp',
            name='IdEDP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mdte',
            name='IdMandante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='odc',
            name='IdODC',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
