# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20160925_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctto',
            name='FechAppCtto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='FechSolCtto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edp',
            name='AprobEDP',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edp',
            name='PeriodEDPTer',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edp',
            name='PresenEDP',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odc',
            name='FechAppOdc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odc',
            name='FechSolOdc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
