# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20160925_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctto',
            name='ObservCtto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
