# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20160925_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odc',
            name='DescripODC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
