# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_auto_20161001_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='edp',
            name='PersHHTotales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
    ]
