# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
