# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-10 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0011_auto_20161008_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[(1, 'Local'), (2, 'No Local')], default='Local', max_length=255),
        ),
    ]
