# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-19 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_auto_20161010_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctto',
            name='NumCtto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ctto',
            name='TipoServ',
            field=models.CharField(blank=True, choices=[('Contrato', 'Contrato'), ('Orden de Servicio', 'Orden de Servicio'), ('Convenio', 'Convenio'), ('Orden de Compra', 'Orden de Compra')], default='Contrato', max_length=25, null=True),
        ),
    ]
