# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-01 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0015_auto_20170401_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctta',
            name='Rep1Ctta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ctta',
            name='Rep2Ctta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ctta',
            name='RutRep1Ctta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ctta',
            name='RutRep2Ctta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
