# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-09 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0017_itemodc'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemodc',
            name='TotalItem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
    ]
