# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-11 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0020_auto_20170410_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenoceco',
            name='CargoDueno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
