# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-12 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0022_auto_20170410_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCtto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumItem', models.CharField(max_length=8)),
                ('DescripItem', models.CharField(blank=True, max_length=50, null=True)),
                ('UnidItem', models.CharField(blank=True, max_length=50, null=True)),
                ('CantItem', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('PuItem', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('TotalItem', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('ObservItem', models.CharField(blank=True, max_length=100, null=True)),
                ('IdCecoCtto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ceco')),
                ('IdCtto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ctto')),
            ],
        ),
    ]
