# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0023_itemctto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctto',
            name='AlcanceCtto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
