# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-15 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0024_ctto_alcancectto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordCtto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCtta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('Cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('Correo', models.CharField(blank=True, max_length=50, null=True)),
                ('Cel', models.CharField(blank=True, max_length=20, null=True)),
                ('CI', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('Cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('Correo', models.CharField(blank=True, max_length=50, null=True)),
                ('Cel', models.CharField(blank=True, max_length=20, null=True)),
                ('CI', models.CharField(blank=True, max_length=20, null=True)),
                ('IdArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Reprentantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdDuenoCeco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ceco')),
            ],
        ),
        migrations.AddField(
            model_name='ctta',
            name='BcoCtta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ctta',
            name='CiudadCtta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ctta',
            name='ComunaCtta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ctta',
            name='FechDocpersonCtta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctta',
            name='GiroCtta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ctta',
            name='NotariapersonCtta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ctta',
            name='NotarioCtta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ctta',
            name='NumCtaCtta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='Anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='Boleta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='DocOferta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='FechCartaAdj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='FechOferta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='IvaOferta',
            field=models.CharField(blank=True, choices=[('IVA', 'Afecto a IVA'), ('NO_IVA', 'No Afecto a IVA'), ('RET_Legal', 'Retención Legal')], default='IVA', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='LugarCtto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='Modalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='MonedaBoleta',
            field=models.CharField(blank=True, choices=[('CLP', 'CLP'), ('USD', 'USD'), ('UF', 'UF'), ('EUR', 'EUR'), ('CAD', 'CAD')], default='CLP', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='RetenCtto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='VigenBoleta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mdte',
            name='CiudadMandte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mdte',
            name='ComunaMandte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mdte',
            name='FechDocpersonMandte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mdte',
            name='NotariapersonMandte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mdte',
            name='NotarioMandte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reprentantes',
            name='IdMandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Mdte'),
        ),
        migrations.AddField(
            model_name='personalctta',
            name='IdCtta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ctta'),
        ),
        migrations.AddField(
            model_name='coordctto',
            name='IdCtto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ctto'),
        ),
        migrations.AddField(
            model_name='coordctto',
            name='IdPersCtta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonalCtta'),
        ),
        migrations.AddField(
            model_name='coordctto',
            name='IdPersProy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonalProyecto'),
        ),
    ]
