# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-15 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0025_auto_20170415_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='AportesCtto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumItem', models.CharField(max_length=8)),
                ('Aporte', models.CharField(blank=True, max_length=50, null=True)),
                ('ObsAporte', models.CharField(blank=True, max_length=50, null=True)),
                ('IdCtto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ctto')),
            ],
        ),
    ]
