# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-15 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0026_aportesctto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportesctto',
            name='Aporte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aportesctto',
            name='ObsAporte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
