# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-16 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0027_auto_20170415_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultasPerClaveCtto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumItem', models.CharField(max_length=8)),
                ('NomPersClave', models.CharField(blank=True, max_length=50, null=True)),
                ('CargPersClave', models.CharField(blank=True, max_length=50, null=True)),
                ('Multa', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True)),
                ('Moneda', models.CharField(blank=True, choices=[('CLP', 'CLP'), ('USD', 'USD'), ('UF', 'UF'), ('EUR', 'EUR'), ('CAD', 'CAD')], default='UF', max_length=5, null=True)),
                ('ObsMulta', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ctto',
            name='AjustNumEDP',
            field=models.CharField(blank=True, default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ctto',
            name='AjustValEDP',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='ctto',
            name='AjusteCom',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=21, null=True),
        ),
        migrations.AddField(
            model_name='multasperclavectto',
            name='IdCtto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ctto'),
        ),
    ]
