# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-19 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0028_auto_20170415_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctto',
            name='FechVigenBoleta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
