# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-30 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0030_auto_20170430_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctto',
            name='CordCtto',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='personas.PersonalProyecto'),
        ),
    ]
