# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-30 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0031_auto_20170430_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctto',
            name='AdminCttoCtta',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='personas.PersonalCtta'),
        ),
    ]
