# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-27 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0033_auto_20170501_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenoceco',
            name='RutDueno',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ctto',
            name='MonedaBoleta',
            field=models.CharField(blank=True, choices=[('CLP', 'CLP'), ('USD', 'USD'), ('UF', 'UF'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('AUD', 'AUD')], default='CLP', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ctto',
            name='MonedaCtto',
            field=models.CharField(blank=True, choices=[('CLP', 'CLP'), ('USD', 'USD'), ('UF', 'UF'), ('EUR', 'EUR'), ('CAD', 'CAD'), ('AUD', 'AUD')], default='CLP', max_length=5, null=True),
        ),
    ]
