# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-28 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0034_auto_20170527_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemctto',
            name='DescripItem',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='itemodc',
            name='DescripItem',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
