# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-04 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0035_auto_20170527_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemctto',
            name='PresupuestoItem',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemodc',
            name='PresupuestoItem',
            field=models.DateField(blank=True, null=True),
        ),
    ]
