# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0036_auto_20170604_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctta',
            name='PaisCtta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ctto',
            name='TipoSolicitud',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Regularización', 'Regularización'), ('Urgente', 'Urgente')], default='Normal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='odc',
            name='FechI_ODC',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odc',
            name='Solicitante',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='personas.PersonalProyecto'),
        ),
        migrations.AlterField(
            model_name='odc',
            name='DescripODC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
