# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-26 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0037_auto_20170615_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAdminProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('Cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('Correo', models.CharField(blank=True, max_length=50, null=True)),
                ('Cel', models.CharField(blank=True, max_length=20, null=True)),
                ('CI', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
