# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-12 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0040_planctto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planctto',
            name='FechEspTecCttoPlan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planctto',
            name='FechIniFlujCttoplan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planctto',
            name='FechIniLictCttoPlan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planctto',
            name='FechIniSerCttoPlan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planctto',
            name='FechLoaCttoPlan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planctto',
            name='FechTerFlujCttoplan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
