# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-12 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0042_auto_20171112_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planctto',
            name='BiderCttoPlan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
