# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-12 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0043_auto_20171112_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planctto',
            name='TipoCttoPlan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
