# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-22 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0044_auto_20171112_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemctto',
            name='CodigoBudgetItem',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemodc',
            name='CodigoBudgetItem',
            field=models.DateField(blank=True, null=True),
        ),
    ]
