# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-22 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0045_auto_20171121_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemctto',
            name='ItemCodBudget',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemodc',
            name='ItemCodBudget',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
